[package]
name = "tauri-plugin-haptics"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "tauri-plugin-haptics"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[target.'cfg(target_os = "android")'.dependencies]
tauri-plugin = { version = "2" }

[features]
default = []
